- name: create sg {{ stack }}-ssh
  ec2_group:
    name: "{{ stack }}-ssh"
    description: Allows ssh access.
    tags: "{'Name': '{{ stack }}-ssh'}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip:
          - 0.0.0.0/0
    rules_egress:
      - proto: -1
        from_port: 0
        to_port: 0
        cidr_ip:
          - 0.0.0.0/0
    state: "{{ state }}"
  when: state == "present"

- name: rm sg {{ stack }}-ssh
  ec2_group:
    name: "{{ stack }}-ssh"
    state: "{{ state }}"
  when: state == "absent"
